#!/usr/bin/env python3
"""
build_options_data.py
=====================
Reads data/cotton_options_history.csv and writes
cotton_options/cotton_options_data.js

Uses JSON encoding so the CSV content is bulletproof — no backtick/escape issues.
"""
import sys, json
from pathlib import Path
from datetime import datetime

REPO_ROOT = Path(__file__).parent.parent
CSV_PATH  = REPO_ROOT / 'data' / 'cotton_options_history.csv'
JS_PATH   = REPO_ROOT / 'cotton_options' / 'cotton_options_data.js'

def log(msg):
    print(msg, flush=True)

def main():
    if not CSV_PATH.exists():
        log(f"CSV not found: {CSV_PATH}")
        log("Upload cotton_options_history.csv to the data/ folder in the repo.")
        sys.exit(0)  # Don't fail the workflow — just skip

    csv_text = CSV_PATH.read_text(encoding='utf-8-sig')  # utf-8-sig strips BOM
    rows = [r for r in csv_text.splitlines() if r.strip()]
    log(f"CSV read: {len(rows):,} rows  ({CSV_PATH.stat().st_size // 1024}KB)")

    # JSON.stringify handles ALL special characters safely — no manual escaping needed
    csv_json = json.dumps(csv_text)

    JS_PATH.parent.mkdir(exist_ok=True)
    js_content = (
        f"// Auto-generated by build_options_data.py — do not edit\n"
        f"// Source: {CSV_PATH.name} ({len(rows):,} rows)\n"
        f"// Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}\n"
        f"window.COTTON_OPTIONS_DATA = {csv_json};\n"
    )
    JS_PATH.write_text(js_content, encoding='utf-8')
    size_kb = JS_PATH.stat().st_size // 1024
    log(f"Written: {JS_PATH} ({size_kb}KB)")
    log(f"First row: {rows[0][:80]}")
    log(f"Second row: {rows[1][:80] if len(rows)>1 else 'N/A'}")

if __name__ == '__main__':
    main()
