#!/usr/bin/env python3
"""
build_options_data.py
=====================
Reads data/cotton_options_history.csv and writes
cotton_options/cotton_options_data.js containing the full CSV
as window.COTTON_OPTIONS_DATA.

The options page loads this via <script src="cotton_options_data.js">
which works on file:// (local) and GitHub Pages (served via HTTP).

Run by GitHub Actions weekly.
Can also be run locally: python scripts/build_options_data.py
"""
import sys
from pathlib import Path
from datetime import datetime

REPO_ROOT = Path(__file__).parent.parent
CSV_PATH  = REPO_ROOT / 'data' / 'cotton_options_history.csv'
JS_PATH   = REPO_ROOT / 'cotton_options' / 'cotton_options_data.js'

def log(msg):
    print(msg, flush=True)

def main():
    if not CSV_PATH.exists():
        log(f'✗ CSV not found: {CSV_PATH}')
        log('  Upload cotton_options_history.csv to data/ folder in the repo.')
        sys.exit(0)  # Don't fail workflow — just skip

    csv_text = CSV_PATH.read_text(encoding='utf-8')
    rows = [r for r in csv_text.splitlines() if r.strip()]
    log(f'✓ CSV read: {len(rows):,} rows  ({CSV_PATH.stat().st_size // 1024}KB)')

    # Escape for embedding in JS template literal
    escaped = csv_text.replace('\\', '\\\\').replace('`', '\\`').replace('${', '\\${')

    JS_PATH.parent.mkdir(exist_ok=True)
    JS_PATH.write_text(
        f'// Auto-generated by build_options_data.py — do not edit\n'
        f'// Source: {CSV_PATH.name} ({len(rows):,} rows)\n'
        f'// Generated: {datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")}\n'
        f'window.COTTON_OPTIONS_DATA = `{escaped}`;\n',
        encoding='utf-8'
    )
    log(f'✓ Written: {JS_PATH} ({JS_PATH.stat().st_size // 1024}KB)')

if __name__ == '__main__':
    main()
