#!/usr/bin/env python3
"""
build_cotton_data.py
====================
Reads cotton_history_1404.csv from the repo root and writes cotton_data.js
containing the entire CSV as a JavaScript string assigned to
window.COTTON_CSV_DATA.

The HTML page loads cotton_data.js via <script src>, which works on both
file:// (local) and GitHub Pages (served via HTTP). The AI assistant then
reads window.COTTON_CSV_DATA automatically on page load.

Run automatically by GitHub Actions after send_report.py.
Can also be run locally:
    python scripts/build_cotton_data.py
"""

import os
import sys
from pathlib import Path

# ── Paths ─────────────────────────────────────────────────────────────────────
REPO_ROOT  = Path(__file__).parent.parent
CSV_PATH   = REPO_ROOT / 'cotton_history_1404.csv'
JS_PATH    = REPO_ROOT / 'cotton_data.js'

def log(msg):
    print(msg, flush=True)

def main():
    if not CSV_PATH.exists():
        log(f'✗ CSV not found: {CSV_PATH}')
        log('  Download it from the dashboard using the "Download cotton_history.csv" button')
        log('  Then commit it to the repo root.')
        sys.exit(0)  # Don't fail the workflow — just skip

    csv_text = CSV_PATH.read_text(encoding='utf-8')
    rows = [r for r in csv_text.splitlines() if r.strip()]
    log(f'✓ CSV read: {len(rows):,} rows ({CSV_PATH.stat().st_size // 1024}KB)')

    # Escape for embedding in a JS string
    # Use backtick template literal to avoid quote escaping
    escaped = csv_text.replace('\\', '\\\\').replace('`', '\\`').replace('${', '\\${')

    js_content = f"""// Auto-generated by build_cotton_data.py — do not edit manually
// Generated from: {CSV_PATH.name} ({len(rows):,} rows)
// To regenerate: python scripts/build_cotton_data.py

window.COTTON_CSV_DATA = `{escaped}`;
"""

    JS_PATH.write_text(js_content, encoding='utf-8')
    size_kb = JS_PATH.stat().st_size // 1024
    log(f'✓ Written: {JS_PATH} ({size_kb}KB)')
    log(f'  The AI assistant will auto-load this data on page open.')

if __name__ == '__main__':
    main()
